---
env:
  browser: true
  es6: true
  jest: true
extends: 
  - atomicjolt
  - 'plugin:@typescript-eslint/recommended'
parser: '@typescript-eslint/parser'
plugins:
  - react
  - jsx-a11y
  - import
  - '@typescript-eslint'
globals:
  describe: false
  beforeAll: false
  beforeEach: false
  afterEach: false
  it: false
  expect: false
  xit: false
  spyOn: false
  jasmine: false
  module: false
  jest: false
  Rollbar: false
  __DEV__: false
  MathJax: false
  require: false
rules: {
  'import/no-extraneous-dependencies': [
      'error',
    {
      devDependencies: [
          '**/*.stories.tsx',
      ],
    },
  ],
  "import/extensions": [2, {
    "stories": "always"
  } ],
  
  "no-use-before-define": "off",
  "@typescript-eslint/no-use-before-define": ["error"],
  
  "no-shadow": "off",
  "@typescript-eslint/no-shadow": ["error"],

  "@typescript-eslint/explicit-module-boundary-types": "off",
  "@typescript-eslint/no-explicit-any": "off",
  "@typescript-eslint/no-empty-interface": "off",
}