// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

import (
	"github.com/atomicjolt/atomic_insight/model"
)

type DiscussionEntryCreatedEvent struct {
	Metadata *model.DiscussionEntryCreatedMetadata `json:"metadata"`
	Body     *model.DiscussionEntryCreatedBody     `json:"body"`
}
