// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

import (
	"github.com/atomicjolt/atomic_insight/model"
)

type DiscussionEntryCreated struct {
	Events []model.DiscussionEntryCreatedEvent `json:"events"`
	Count  int                                 `json:"count"`
}

type Empty struct {
	Dummy int `json:"dummy"`
}
